### ISSUE TITLE
Make waitUntil value configurable

### ISSUE THREAD

**Issue by peterjaap** [BuilderIO/SSDiff#2]
It's now hard-coded to `networkidle0`, but I'd like to use `domcontentloaded`

https://github.com/BuilderIO/SSDiff/blob/main/src/index.ts#L150

**Comment by gijsdb** [comment]
I am interested in tackling this issue if you want it added

**Comment by peterjaap** [comment]
Yes please!

**Comment by gijsdb** [comment]
@akshatgarg12 This issue can be closed now.
